from dataclasses import dataclass
from infrastructure.cqrs.IQuery import IQuery
from domain.operation.GetDataOperationJobExecutionLogList.GetDataOperationJobExecutionLogListRequest import GetDataOperationJobExecutionLogListRequest
from domain.operation.GetDataOperationJobExecutionLogList.GetDataOperationJobExecutionLogListResponse import GetDataOperationJobExecutionLogListResponse


@dataclass
class GetDataOperationJobExecutionLogListQuery(IQuery[GetDataOperationJobExecutionLogListResponse]):
    request: GetDataOperationJobExecutionLogListRequest = None
