from typing import List
from domain.common.decorators.responseclass import responseclass
from domain.operation.GetDataOperationJobExecutionLogList.GetDataOperationJobExecutionLogListDto import GetDataOperationJobExecutionLogListDto


@responseclass
class GetDataOperationJobExecutionLogListResponse:
	Data: List[GetDataOperationJobExecutionLogListDto] = None
