version: "3.8"

services:
  postgresql:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=pdi
      - PG_TRUST_LOCALNET=true
    volumes:
      - /var/lib/pdipostgresql/data
  
  pdi-notification:
    image: ${REGISTRY:-pythondataintegrator}/notification:${TAG:-latest}
    build: 
      context: src/notification/
      dockerfile: Dockerfile
    ports:
      - '7500:7500'
    environment:
      - APPLICATION_ENVIRONMENT=TEST
      - TZ=Europe/Istanbul

  pdi-api:
    image: ${REGISTRY:-pythondataintegrator}/api:${TAG:-latest}
    build: 
      context: src/api/
      dockerfile: Dockerfile
    ports:
      - '7100:7100'
    environment:
      - APPLICATION_ENVIRONMENT=TEST
      - DATABASE_TYPE=POSTGRESQL
      - DATABASE_HOST=postgresql
      - DATABASE_DATABASE=pdi
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=123456
      - DATABASE_PORT=5432
      - SCHEDULER_RPC_CLIENT_HOST=pdi-scheduler
      - PROCESS_RPC_CLIENT_HOST=pdi-process
      - NOTIFICATION_CLIENT_HOST=http://pdi-notification:7500
      - TZ=Europe/Istanbul
      - UPGRADE_DATABASE=true
    depends_on:
      - postgresql

  pdi-process:
    image: ${REGISTRY:-pythondataintegrator}/process:${TAG:-latest}
    build: 
      context: src/process/
      dockerfile: Dockerfile
    ports:
      - '7400:7400'
    environment:
      - APPLICATION_ENVIRONMENT=TEST
      - DATABASE_TYPE=POSTGRESQL
      - DATABASE_HOST=postgresql
      - DATABASE_DATABASE=pdi
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=123456
      - DATABASE_PORT=5432
      - NOTIFICATION_CLIENT_HOST=http://pdi-notification:7500
      - TZ=Europe/Istanbul
    depends_on:
      - postgresql

  pdi-scheduler:
    image: ${REGISTRY:-pythondataintegrator}/scheduler:${TAG:-latest}
    build: 
      context: src/scheduler/
      dockerfile: Dockerfile
    ports:
      - '7300:7300'
    environment:
      - APPLICATION_ENVIRONMENT=TEST
      - DATABASE_TYPE=POSTGRESQL
      - DATABASE_HOST=postgresql
      - DATABASE_DATABASE=pdi
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=123456
      - DATABASE_PORT=5432
      - PROCESS_RPC_CLIENT_HOST=pdi-process
      - TZ=Europe/Istanbul
    depends_on:
      - postgresql
      - pdi-api
      - pdi-process
  
  pdi-ui:
    image: ${REGISTRY:-pythondataintegrator}/ui:${TAG:-latest}
    build:
      context: src/ui/
      dockerfile: Dockerfile
    ports:
      - '7000:7000'
    environment:
      - AUTHORITY=http://localhost:7001/
      - CLIENT_ID=http://localhost:7001/
      - REDIRECT_URI=http://localhost:7000/oidc-login-redirect
      - POST_REDIRECT_URI=http://localhost:7000/?postLogout=true
      - SLIENT_REDIRECT_URI=http://localhost:7000/oidc-slient-refresh
      - API_URI=http://localhost:7100/
      - NOTIFICATION_URI=http://localhost:7500/
    volumes:
      - '/app/node_modules'
      - ./src/ui/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - postgresql