"""bigdata

Revision ID: 5ba56f7f0943
Revises: 8f3ddc689ab5
Create Date: 2022-01-06 23:38:04.931000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba56f7f0943'
down_revision = '8f3ddc689ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ConnectionBigData',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('ConnectionId', sa.Integer(), nullable=True),
    sa.Column('ConnectorTypeId', sa.Integer(), nullable=True),
    sa.Column('DatabaseName', sa.String(length=100), nullable=True),
    sa.Column('Ssl', sa.Boolean(), nullable=True),
    sa.Column('UseOnlySspi', sa.Boolean(), nullable=True),
    sa.Column('CreatedByUserId', sa.Integer(), nullable=False),
    sa.Column('CreationDate', sa.DateTime(), nullable=False),
    sa.Column('LastUpdatedUserId', sa.Integer(), nullable=True),
    sa.Column('LastUpdatedDate', sa.DateTime(), nullable=True),
    sa.Column('IsDeleted', sa.Integer(), nullable=False),
    sa.Column('Comments', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['ConnectionId'], ['Connection.Connection.Id'], ),
    sa.ForeignKeyConstraint(['ConnectorTypeId'], ['Connection.ConnectorType.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    schema='Connection'
    )
    op.create_table('DataIntegrationConnectionBigData',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('DataIntegrationConnectionId', sa.Integer(), nullable=True),
    sa.Column('Schema', sa.String(length=100), nullable=True),
    sa.Column('TableName', sa.String(length=100), nullable=True),
    sa.Column('Query', sa.Text(), nullable=True),
    sa.Column('CreatedByUserId', sa.Integer(), nullable=False),
    sa.Column('CreationDate', sa.DateTime(), nullable=False),
    sa.Column('LastUpdatedUserId', sa.Integer(), nullable=True),
    sa.Column('LastUpdatedDate', sa.DateTime(), nullable=True),
    sa.Column('IsDeleted', sa.Integer(), nullable=False),
    sa.Column('Comments', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['DataIntegrationConnectionId'], ['Integration.DataIntegrationConnection.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    schema='Integration'
    )
    op.create_table('SecretSourceKerberosAuthentication',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('SecretSourceId', sa.Integer(), nullable=True),
    sa.Column('Principal', sa.Text(), nullable=False),
    sa.Column('Password', sa.Text(), nullable=False),
    sa.Column('KrbRealm', sa.Text(), nullable=False),
    sa.Column('KrbFqdn', sa.Text(), nullable=False),
    sa.Column('KrbServiceName', sa.Text(), nullable=False),
    sa.Column('CreatedByUserId', sa.Integer(), nullable=False),
    sa.Column('CreationDate', sa.DateTime(), nullable=False),
    sa.Column('LastUpdatedUserId', sa.Integer(), nullable=True),
    sa.Column('LastUpdatedDate', sa.DateTime(), nullable=True),
    sa.Column('IsDeleted', sa.Integer(), nullable=False),
    sa.Column('Comments', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['SecretSourceId'], ['Secret.SecretSource.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    schema='Secret'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SecretSourceKerberosAuthentication', schema='Secret')
    op.drop_table('DataIntegrationConnectionBigData', schema='Integration')
    op.drop_table('ConnectionBigData', schema='Connection')
    # ### end Alembic commands ###
