"""pre_post_procedure_remove

Revision ID: e2bcfbd775cb
Revises: 3b88f8ca0cb7
Create Date: 2021-03-01 01:12:45.515393

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2bcfbd775cb'
down_revision = '3b88f8ca0cb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DataIntegrationExecutionJob', schema='Integration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DataIntegrationExecutionJob',
                    sa.Column('Id', sa.INTEGER(), server_default=sa.text(
                        'nextval(\'"Integration"."PythonDataIntegrationExecutionJob_Id_seq"\'::regclass)'),
                              autoincrement=True, nullable=False),
                    sa.Column('DataIntegrationId', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('ExecutionProcedure', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
                    sa.Column('IsPre', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('IsPost', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('CreatedByUserId', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('CreationDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.Column('LastUpdatedUserId', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('LastUpdatedDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('IsDeleted', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('Comments', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
                    sa.Column('RowVersion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['DataIntegrationId'], ['Integration.DataIntegration.Id'],
                                            name='DataIntegrationExecutionJob_DataIntegrationId_fkey'),
                    sa.PrimaryKeyConstraint('Id', name='DataIntegrationExecutionJob_pkey'),
                    schema='Integration'
                    )
    # ### end Alembic commands ###
