from pdip.cqrs.decorators import responseclass
from domain.operation.GetDataOperationJobExecution.GetDataOperationJobExecutionDto import GetDataOperationJobExecutionDto


@responseclass
class GetDataOperationJobExecutionResponse:
	Data: GetDataOperationJobExecutionDto = None
