from dataclasses import dataclass
from pdip.cqrs import IQuery
from domain.operation.GetDataOperationJobExecution.GetDataOperationJobExecutionRequest import GetDataOperationJobExecutionRequest
from domain.operation.GetDataOperationJobExecution.GetDataOperationJobExecutionResponse import GetDataOperationJobExecutionResponse


@dataclass
class GetDataOperationJobExecutionQuery(IQuery[GetDataOperationJobExecutionResponse]):
    request: GetDataOperationJobExecutionRequest = None
