"""connection_unique_false

Revision ID: 754632afb373
Revises: 5692deba1dbf
Create Date: 2021-02-21 22:24:56.997648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '754632afb373'
down_revision = '5692deba1dbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Connection_Connection_Name', table_name='Connection', schema='Connection')
    op.create_index(op.f('ix_Connection_Connection_Name'), 'Connection', ['Name'], unique=False, schema='Connection')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Connection_Connection_Name'), table_name='Connection', schema='Connection')
    op.create_index('ix_Connection_Connection_Name', 'Connection', ['Name'], unique=True, schema='Connection')
    # ### end Alembic commands ###
