"""baseline

Revision ID: 949449ad259e
Revises: 754632afb373
Create Date: 2021-02-22 22:09:42.540014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949449ad259e'
down_revision = '754632afb373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
