"""file_csv_improvments

Revision ID: a0968e52f6b3
Revises: e50ccd73d9c9
Create Date: 2021-03-16 02:45:45.086872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0968e52f6b3'
down_revision = 'e50ccd73d9c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DataIntegrationConnectionFileCsv',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('DataIntegrationConnectionFileId', sa.Integer(), nullable=True),
    sa.Column('HasHeader', sa.Boolean(), nullable=False),
    sa.Column('Header', sa.String(length=4000), nullable=True),
    sa.Column('Separator', sa.String(length=10), nullable=False),
    sa.Column('CreatedByUserId', sa.Integer(), nullable=False),
    sa.Column('CreationDate', sa.DateTime(), nullable=False),
    sa.Column('LastUpdatedUserId', sa.Integer(), nullable=True),
    sa.Column('LastUpdatedDate', sa.DateTime(), nullable=True),
    sa.Column('IsDeleted', sa.Integer(), nullable=False),
    sa.Column('Comments', sa.String(length=1000), nullable=True),
    sa.Column('RowVersion', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['DataIntegrationConnectionFileId'], ['Integration.DataIntegrationConnectionFile.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    schema='Integration'
    )
    op.add_column('ConnectionFile', sa.Column('Host', sa.String(length=100), nullable=True), schema='Connection')
    op.add_column('ConnectionFile', sa.Column('Port', sa.Integer(), nullable=True), schema='Connection')
    op.drop_column('ConnectionFile', 'Folder', schema='Connection')
    op.add_column('DataIntegrationConnectionFile', sa.Column('Folder', sa.String(length=100), nullable=True), schema='Integration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DataIntegrationConnectionFile', 'Folder', schema='Integration')
    op.add_column('ConnectionFile', sa.Column('Folder', sa.VARCHAR(length=100), autoincrement=False, nullable=True), schema='Connection')
    op.drop_column('ConnectionFile', 'Port', schema='Connection')
    op.drop_column('ConnectionFile', 'Host', schema='Connection')
    op.drop_table('DataIntegrationConnectionFileCsv', schema='Integration')
    # ### end Alembic commands ###
