APPLICATION:
  ENVIRONMENT: DEVELOPMENT
  NAME: Pdi Process Server
  SECRET_KEY: s4GGU7jFnKjgu1LsK7fUdxOp1DUSQ-PVgvr28rBNAHM=

DATABASE:
  #POSTGRESQL local environment
  TYPE: POSTGRESQL
  HOST: 10.220.13.77
  PORT: 5432
  DATABASE: pdi
  USERNAME: pdi_user
  PASSWORD: PWD_011


PROCESS_RPC_SERVER:
  PROTOCOL_CONFIG:
    allow_public_attrs: True
    sync_request_timeout: 60
  PORT: 7400