from dataclasses import dataclass

from domain.connection.CheckDatabaseConnectionTableRowCount.CheckDatabaseConnectionTableRowCountRequest import CheckDatabaseConnectionTableRowCountRequest
from infrastructure.cqrs.ICommand import ICommand


@dataclass
class CheckDatabaseConnectionTableRowCountCommand(ICommand):
    request: CheckDatabaseConnectionTableRowCountRequest = None
