from pdip.cqrs.decorators import responseclass
from domain.dashboard.GetSourceDataAffectedRowWidget.GetSourceDataAffectedRowWidgetDto import GetSourceDataAffectedRowWidgetDto


@responseclass
class GetSourceDataAffectedRowWidgetResponse:
	Data: GetSourceDataAffectedRowWidgetDto = None
