APPLICATION:
  ENVIRONMENT: DEVELOPMENT
  NAME: Pdi Api
  SECRET_KEY: s4GGU7jFnKjgu1LsK7fUdxOp1DUSQ-PVgvr28rBNAHM=

DATABASE:
  #POSTGRESQL local environment
  TYPE: POSTGRESQL
  HOST: 10.220.13.77
  PORT: 5432
  DATABASE: pdi
  USERNAME: pdi_user
  PASSWORD: PWD_011

API:
  IS_DEBUG: False
  PORT: 7100
  AUTHORIZATIONS:
    oauth2:
      type: oauth2
      flow: password
      tokenUrl: https://tokenmicroservicetst.turkcell.com.tr/connect/token
      authorizationUrl: https://tokenmicroservicetst.turkcell.com.tr/connect/authorize
      scopes:
        pdi.api: Api grant
        offline_access: Grant read-only access
  SECURITY:
    oauth2: pdi.api
  AUTHORITY: 'https://tokenmicroservicetst.turkcell.com.tr'
  AUDIENCE: 'LocationShare.WebApi'
  SCOPES:
    - 'LocationShare.WebApi'

SCHEDULER_RPC_CLIENT:
  HOST: localhost
  PORT: 7300

PROCESS_RPC_CLIENT:
  HOST: localhost
  PORT: 7400