APPLICATION:
  ENVIRONMENT: DEVELOPMENT
  NAME: Pdi Api
  SECRET_KEY: s4GGU7jFnKjgu1LsK7fUdxOp1DUSQ-PVgvr28rBNAHM=

DATABASE:
  #POSTGRESQL local environment
  TYPE: POSTGRESQL
  HOST: localhost
  PORT: 5432
  DATABASE: pdi
  USERNAME: postgres
  PASSWORD: 123456

API:
  IS_DEBUG: False
  PORT: 7100

SCHEDULER_RPC_CLIENT:
  HOST: localhost
  PORT: 7300