DATABASE:
  #POSTGRESQL local environment
  TYPE: POSTGRESQL
  HOST: localhost
  PORT: 5432
  DATABASE: pdi
  USERNAME: postgres
  PASSWORD: 123456

API:
  ENVIRONMENT: DEVELOPMENT
  NAME: Pdi Application(Python Data Integrator)
  IS_DEBUG: False
  PORT: 7100
  SECRET_KEY: s4GGU7jFnKjgu1LsK7fUdxOp1DUSQ-PVgvr28rBNAHM=

APS:
  COALESCE: False
  MAX_INSTANCES: 10
  THREAD_POOL_EXECUTER_COUNT: 10
  PROCESS_POOL_EXECUTER_COUNT: 10
  DEFAULT_MISFIRE_GRACE_TIME_DATE_JOB: 60000
  DEFAULT_MISFIRE_GRACE_TIME_CRON_JOB: 300

APPLICATION:
  API_NODE: True
  PROCESS_NODE: False