"""data_integration_queue

Revision ID: 140a433af6c5
Revises: d0e0fa244e63
Create Date: 2021-03-22 03:45:05.573606

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '140a433af6c5'
down_revision = 'd0e0fa244e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DataIntegrationConnectionQueue',
                    sa.Column('Id', sa.Integer(), nullable=False),
                    sa.Column('DataIntegrationConnectionId', sa.Integer(), nullable=True),
                    sa.Column('TopicName', sa.String(length=200), nullable=True),
                    sa.Column('CreatedByUserId', sa.Integer(), nullable=False),
                    sa.Column('CreationDate', sa.DateTime(), nullable=False),
                    sa.Column('LastUpdatedUserId', sa.Integer(), nullable=True),
                    sa.Column('LastUpdatedDate', sa.DateTime(), nullable=True),
                    sa.Column('IsDeleted', sa.Integer(), nullable=False),
                    sa.Column('Comments', sa.String(length=1000), nullable=True),
                    sa.Column('RowVersion', sa.TIMESTAMP(), nullable=True),
                    sa.ForeignKeyConstraint(['DataIntegrationConnectionId'],
                                            ['Integration.DataIntegrationConnection.Id'], ),
                    sa.PrimaryKeyConstraint('Id'),
                    schema='Integration'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DataIntegrationConnectionQueue', schema='Integration')
    # ### end Alembic commands ###
