from dataclasses import dataclass
from infrastructure.cqrs.IQuery import IQuery
from domain.dashboard.GetDataOperationJobWidget.GetDataOperationJobWidgetRequest import GetDataOperationJobWidgetRequest
from domain.dashboard.GetDataOperationJobWidget.GetDataOperationJobWidgetResponse import GetDataOperationJobWidgetResponse


@dataclass
class GetDataOperationJobWidgetQuery(IQuery[GetDataOperationJobWidgetResponse]):
    request: GetDataOperationJobWidgetRequest = None
