name: Docker Image CI

on:
  push:
    branches: [ feature/ui-improvments ]
  pull_request:
    branches: [ feature/ui-improvments ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose -f "docker-compose.yml" up -d --build
